import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  ru: {
    appName: 'DubaiEstate AI',
    subtitle: 'Для риэлторов Дубая',
    greeting: 'Привет',
    greetingEnd: '👋',
    loading: 'Загрузка...',
    newProject: 'Новый проект',
    projects: 'Ваши проекты',
    noProjects: 'Нет проектов',
    createFirstProject: 'Создайте свой первый проект, загрузив чертеж квартиры',
    createProject: 'Создать проект',
    subscribe: 'Оформить подписку',
    login: 'Войти',
    features: 'Возможности',
    pricing: 'Подписка',
    perMonth: '/мес',
    bestChoice: 'Лучший выбор',
    cancelAnytime: 'Оплата через Stripe. Отмена в любой момент.',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    premiumActive: 'Premium активен',
    connectedChannels: 'Подключенные каналы',
    management: 'Управление',
    subscribers: 'подписчиков',
    totalObjects: 'Всего объектов',
    rendersCreated: 'Рендеров создано',
    channelConnected: 'Нет подключенных каналов',
    connectChannel: 'Подключить канал',
    howToConnect: 'Как подключить?',
    projectCreated: 'Проект сохранен локально',
    draftSaved: 'Черновик сохранен',
    generating: 'Генерация...',
    generate: 'Сгенерировать',
    regenerate: 'Перегенерировать',
    copy: 'Копировать',
    copied: 'Скопировано!',
    post: 'Опубликовать',
    chooseChannel: 'Выберите канал',
    noChannels: 'Нет подключенных каналов',
    selectChannel: 'Выберите канал для публикации',
    published: 'Опубликовано в канал!',
    step: 'Шаг',
    from: 'из',
    continue: 'Продолжить',
    uploadBlueprint: 'Загрузите чертеж',
    blueprintDesc: 'Загрузите план квартиры для создания 3D визуализации',
    dragDrop: 'Перетащите файл сюда',
    orClick: 'или нажмите для выбора',
    maxSize: 'Поддерживает: JPG, PNG, PDF (до 10 МБ)',
    details: 'Основные детали',
    detailsDesc: 'Укажите характеристики объекта',
    propertyType: 'Тип недвижимости',
    bedrooms: 'Спальни',
    bathrooms: 'Санузлы',
    area: 'Площадь',
    sqft: 'кв. фут',
    sqm: 'кв. м',
    location: 'Расположение',
    locationDesc: 'Укажите локацию объекта',
    district: 'Район / Сообщество',
    tower: 'Башня / Комплекс',
    renderStyle: 'Стиль рендера',
    price: 'Цена',
    priceDesc: 'Укажите цену объекта',
    currency: 'Валюта',
    save: 'Сохранить',
    settings: 'Настройки',
    profile: 'Профиль',
    channels: 'Каналы',
    addChannel: 'Добавить',
    remove: 'Отключить',
    botUsername: 'Наш бот для постинга:',
    addBotAdmin: 'Добавьте бота как администратора в канал для публикации объектов',
    language: 'Язык интерфейса',
    russian: 'Русский',
    english: 'Английский',
    support: 'Поддержка',
    telegramChat: 'Telegram чат',
    help: 'Получите помощь',
    logout: 'Выйти из аккаунта',
    draft: 'Чертеж',
    render3d: '3D Визуализация',
    aiPowered: 'AI Powered',
    modern: 'Современный',
    luxury: 'Люкс',
    minimalist: 'Минимализм',
    arabic: 'Арабский стиль',
    scandinavian: 'Скандинавский',
    apartment: 'Квартира',
    villa: 'Вилла',
    penthouse: 'Пентхаус',
    studio: 'Студия',
    townhouse: 'Таунхаус',
    bedroomsOptions: ['Студия', '1 спальня', '2 спальни', '3 спальни', '4+ спальни'],
    bathroomsOptions: ['1 санузел', '2 санузла', '3+ санузла'],
    unlimitedRenders: 'Безлимитные 3D рендеры',
    textGeneration: 'Генерация текстов',
    autoPosting: 'Автопостинг в каналы',
    saveProjects: 'Сохраняйте проекты',
    prioritySupport: 'Приоритетная поддержка',
    apartmentLower: 'квартира',
    villaLower: 'вилла',
    penthouseLower: 'пентхаус',
    studioLower: 'студия',
    townhouseLower: 'таунхаус',
    bedroomsLower: 'сп.',
    sqftLower: 'кв. фут',
    locationLower: 'локация',
    priceLower: 'цена',
    description: 'Описание объекта',
    quickTemplates: 'Быстрые шаблоны',
    emphasizeView: 'Подчеркнуть вид',
    emphasizeRenovation: 'Акцент на ремонт',
    investmentPotential: 'Инвестиционный потенциал',
    familyProperty: 'Семейная недвижимость'
  },
  en: {
    appName: 'DubaiEstate AI',
    subtitle: 'For Dubai Real Estate Agents',
    greeting: 'Hello',
    greetingEnd: '👋',
    loading: 'Loading...',
    newProject: 'New Project',
    projects: 'Your Projects',
    noProjects: 'No Projects',
    createFirstProject: 'Create your first project by uploading a floor plan',
    createProject: 'Create Project',
    subscribe: 'Subscribe',
    login: 'Login',
    features: 'Features',
    pricing: 'Subscription',
    perMonth: '/month',
    bestChoice: 'Best Value',
    cancelAnytime: 'Payment via Stripe. Cancel anytime.',
    alreadyHaveAccount: 'Already have an account?',
    premiumActive: 'Premium Active',
    connectedChannels: 'Connected Channels',
    management: 'Manage',
    subscribers: 'subscribers',
    totalObjects: 'Total Properties',
    rendersCreated: 'Renders Created',
    channelConnected: 'No connected channels',
    connectChannel: 'Connect Channel',
    howToConnect: 'How to connect?',
    projectCreated: 'Project saved locally',
    draftSaved: 'Draft saved',
    generating: 'Generating...',
    generate: 'Generate',
    regenerate: 'Regenerate',
    copy: 'Copy',
    copied: 'Copied!',
    post: 'Post',
    chooseChannel: 'Select Channel',
    noChannels: 'No channels connected',
    selectChannel: 'Select a channel to publish',
    published: 'Posted to channel!',
    step: 'Step',
    from: 'of',
    continue: 'Continue',
    uploadBlueprint: 'Upload Floor Plan',
    blueprintDesc: 'Upload your apartment floor plan to create 3D visualization',
    dragDrop: 'Drop file here',
    orClick: 'or click to select',
    maxSize: 'Supports: JPG, PNG, PDF (up to 10 MB)',
    details: 'Property Details',
    detailsDesc: 'Specify property characteristics',
    propertyType: 'Property Type',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    area: 'Area',
    sqft: 'sq ft',
    sqm: 'sq m',
    location: 'Location',
    locationDesc: 'Specify property location',
    district: 'District / Community',
    tower: 'Tower / Complex',
    renderStyle: 'Render Style',
    price: 'Price',
    priceDesc: 'Specify property price',
    currency: 'Currency',
    save: 'Save',
    settings: 'Settings',
    profile: 'Profile',
    channels: 'Channels',
    addChannel: 'Add',
    remove: 'Disconnect',
    botUsername: 'Our posting bot:',
    addBotAdmin: 'Add the bot as administrator to your channel to publish listings',
    language: 'Interface Language',
    russian: 'Russian',
    english: 'English',
    support: 'Support',
    telegramChat: 'Telegram Chat',
    help: 'Get Help',
    logout: 'Logout',
    draft: 'Floor Plan',
    render3d: '3D Render',
    aiPowered: 'AI Powered',
    modern: 'Modern',
    luxury: 'Luxury',
    minimalist: 'Minimalist',
    arabic: 'Arabic Style',
    scandinavian: 'Scandinavian',
    apartment: 'Apartment',
    villa: 'Villa',
    penthouse: 'Penthouse',
    studio: 'Studio',
    townhouse: 'Townhouse',
    bedroomsOptions: ['Studio', '1 Bedroom', '2 Bedrooms', '3 Bedrooms', '4+ Bedrooms'],
    bathroomsOptions: ['1 Bathroom', '2 Bathrooms', '3+ Bathrooms'],
    unlimitedRenders: 'Unlimited 3D Renders',
    textGeneration: 'Text Generation',
    autoPosting: 'Auto-posting to Channels',
    saveProjects: 'Save Projects',
    prioritySupport: 'Priority Support',
    apartmentLower: 'apartment',
    villaLower: ' villa',
    penthouseLower: 'penthouse',
    studioLower: 'studio',
    townhouseLower: 'townhouse',
    bedroomsLower: 'bed',
    sqftLower: 'sq ft',
    locationLower: 'location',
    priceLower: 'price',
    description: 'Property Description',
    quickTemplates: 'Quick Templates',
    emphasizeView: 'Emphasize View',
    emphasizeRenovation: 'Highlight Renovation',
    investmentPotential: 'Investment Potential',
    familyProperty: 'Family Property'
  }
}

const LanguageContext = createContext(null)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('ru')

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language')
      if (saved && ['ru', 'en'].includes(saved)) {
        setLanguage(saved)
      } else {
        const browserLang = navigator.language?.split('-')[0]
        if (browserLang === 'en') setLanguage('en')
      }
    }
  }, [])

  const changeLanguage = (lang) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
      document.documentElement.lang = lang
      document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    }
  }

  const t = (key) => translations[language][key] || key

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
